graph LR
    subgraph OLD["<b>Analytics Era: RBAC</b>"]
        TITLE1["<b>Role-Based Access Control</b>"]
        R1["<b>User Request</b>"]
        R2["<b>Check Role</b>"]
        R3["<b>Role = Patient</b>"]
        R4["<b>Grant Broad Access</b>"]
        R5["<b>Violates minimum <br/>necessary access</b>"]
        
        TITLE1 --> R1
        R1 --> R2
        R2 --> R3
        R3 --> R4
        R4 --> R5
    end
    
    OLD -.->|<b>Evolution</b>| NEW
    
    subgraph NEW["<b>Agent Era: ABAC</b>"]
        TITLE2["<b>Attribute-Based Access Control</b>"]
        A1["<b>User Request</b>"]
        A2["<b>Context Eval</b><br/><b>Who • What • When <br/> Where • Why</b>"]
        A3["<b>Dynamic Policy</b>"]
        A4["<b>Filter Rows</b>"]
        A5["<b>Sub-10ms secure access</b>"]
        
        TITLE2 --> A1
        A1 --> A2
        A2 --> A3
        A3 --> A4
        A4 --> A5
    end
    
    style TITLE1 fill:#EB898B,stroke:none,color:#0D0D0D,rx:10,ry:10
    style R1 fill:#EB898B,stroke:none,color:#0D0D0D,rx:10,ry:10
    style R2 fill:#EB898B,stroke:none,color:#0D0D0D,rx:10,ry:10
    style R3 fill:#EB898B,stroke:none,color:#0D0D0D,rx:10,ry:10
    style R4 fill:#EB898B,stroke:none,color:#0D0D0D,rx:10,ry:10
    style R5 fill:#EB898B,stroke:none,color:#0D0D0D,rx:10,ry:10
    
    style TITLE2 fill:#14D793,stroke:none,color:#0D0D0D,rx:10,ry:10
    style A1 fill:#14D793,stroke:none,color:#0D0D0D,rx:10,ry:10
    style A2 fill:#14D793,stroke:none,color:#0D0D0D,rx:10,ry:10
    style A3 fill:#14D793,stroke:none,color:#0D0D0D,rx:10,ry:10
    style A4 fill:#14D793,stroke:none,color:#0D0D0D,rx:10,ry:10
    style A5 fill:#14D793,stroke:none,color:#0D0D0D,rx:10,ry:10
    
    style OLD fill:#EB898B,stroke:#EB898B,stroke-width:1px,color:#0D0D0D,rx:20,ry:20
    style NEW fill:#14D793,stroke:#14D793,stroke-width:1px,color:#0D0D0D,rx:20,ry:20
    
    Copyright["<b>© 2025 Colaberry Inc.</b>"]
    style Copyright fill:none,stroke:none,color:#0D0D0D
